codecov:
  require_ci_to_pass: yes

coverage:
  range: 50..100
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
    changes: false

comment: off
