path_classifiers:
  library:
    - versioneer.py  # Set Versioneer.py to an external "library" (3rd party code)
    - setup.py
  test:
    - tests
  docs:
    - docs
  generated:
    - quimb/_version.py
