"""Quantum circuit simulation using tensor networks.

This subpackage re-exports all the main classes and functions as if it were
a single module.
"""

from .core import (
    CircuitBase,
)
from .exact import (
    Circuit,
    CircuitDense,
)
from .gates import (
    ALL_GATES,
    ALL_PARAM_GATES,
    CONSTANT_GATES,
    GATE_SIZE,
    GATE_TAGS,
    ONE_QUBIT_GATES,
    ONE_QUBIT_PARAM_GATES,
    PARAM_GATES,
    SPECIAL_GATES,
    TWO_QUBIT_GATES,
    TWO_QUBIT_PARAM_GATES,
    Gate,
    apply_controlled_gate,
    apply_swap,
    build_controlled_gate_htn,
    crx_param_gen,
    cry_param_gen,
    crz_param_gen,
    cu1_param_gen,
    cu2_param_gen,
    cu3_param_gen,
    fsim_param_gen,
    fsimg_param_gen,
    givens2_param_gen,
    givens_param_gen,
    parse_to_gate,
    recursive_stack,
    register_constant_gate,
    register_param_gate,
    register_special_gate,
    rehearsal_dict,
    rx_gate_param_gen,
    rxx_param_gen,
    ry_gate_param_gen,
    ryy_param_gen,
    rz_gate_param_gen,
    rzz_param_gen,
    sample_bitstring_from_prob_ndarray,
    su4_gate_param_gen,
    u1_gate_param_gen,
    u2_gate_param_gen,
    u3_gate_param_gen,
    xx_minus_yy_param_gen,
    xx_plus_yy_param_gen,
)
from .mps import (
    CircuitMPS,
    CircuitMPSLazy,
    CircuitPermMPS,
)
from .pepo import (
    CircuitPEPOSimpleUpdate,
)
from .peps import (
    CircuitPEPSSimpleUpdate,
)
from .qasm import (
    get_openqasm2_regexes,
    get_openqasm3_regexes,
    multi_replace,
    parse_openqasm2_file,
    parse_openqasm2_str,
    parse_openqasm2_url,
    parse_openqasm3_file,
    parse_openqasm3_str,
    parse_openqasm3_url,
    parse_qsim_file,
    parse_qsim_str,
    parse_qsim_url,
    to_clean_list,
)

# pin canonical module path (pickle + Sphinx xref stability)
for _cls in (
    CircuitBase,
    Circuit,
    CircuitDense,
    CircuitMPS,
    CircuitMPSLazy,
    CircuitPEPOSimpleUpdate,
    CircuitPEPSSimpleUpdate,
    CircuitPermMPS,
    Gate,
):
    _cls.__module__ = "quimb.tensor.circuit"
del _cls

__all__ = (
    "ALL_GATES",
    "ALL_PARAM_GATES",
    "apply_controlled_gate",
    "apply_swap",
    "build_controlled_gate_htn",
    "Circuit",
    "CircuitDense",
    "CircuitMPS",
    "CircuitMPSLazy",
    "CircuitBase",
    "CircuitPEPOSimpleUpdate",
    "CircuitPEPSSimpleUpdate",
    "CircuitPermMPS",
    "CONSTANT_GATES",
    "crx_param_gen",
    "cry_param_gen",
    "crz_param_gen",
    "cu1_param_gen",
    "cu2_param_gen",
    "cu3_param_gen",
    "fsim_param_gen",
    "fsimg_param_gen",
    "GATE_SIZE",
    "GATE_TAGS",
    "Gate",
    "get_openqasm2_regexes",
    "get_openqasm3_regexes",
    "givens_param_gen",
    "givens2_param_gen",
    "multi_replace",
    "ONE_QUBIT_GATES",
    "ONE_QUBIT_PARAM_GATES",
    "PARAM_GATES",
    "parse_openqasm2_file",
    "parse_openqasm2_str",
    "parse_openqasm2_url",
    "parse_openqasm3_file",
    "parse_openqasm3_str",
    "parse_openqasm3_url",
    "parse_qsim_file",
    "parse_qsim_str",
    "parse_qsim_url",
    "parse_to_gate",
    "recursive_stack",
    "register_constant_gate",
    "register_param_gate",
    "register_special_gate",
    "rehearsal_dict",
    "rx_gate_param_gen",
    "rxx_param_gen",
    "ry_gate_param_gen",
    "ryy_param_gen",
    "rz_gate_param_gen",
    "rzz_param_gen",
    "sample_bitstring_from_prob_ndarray",
    "SPECIAL_GATES",
    "su4_gate_param_gen",
    "to_clean_list",
    "TWO_QUBIT_GATES",
    "TWO_QUBIT_PARAM_GATES",
    "u1_gate_param_gen",
    "u2_gate_param_gen",
    "u3_gate_param_gen",
    "xx_minus_yy_param_gen",
    "xx_plus_yy_param_gen",
)
