blank_issues_enabled: false
contact_links:
  - name: Usage question
    url: https://github.com/jcmgray/quimb/discussions
    about: |
      Ask questions and discuss with other community members here.
      If you have a question then please include a self-contained reproducible
      example if possible.
